# I. Struktur Data

## 1. List

### List

In Python, alist is the main data structure used to store a mutable sequence of elements. The seuence of data elements stored in the list need not be of the same type.

In [1]:
aList = ["John", 33,"Toronto", True]

In [2]:
aList

['John', 33, 'Toronto', True]

In [3]:
type(aList)

list

In [4]:
bin_colors=['Red','Green','Blue','Yellow']

## 2. Tuples

### Tuples

The second data structure that can be used to store a collection is tuple in contrast to list, tuples are immutables (read-only) data structure. Tuples consist of several elements surronded by()

Like list, elementts within a tuple can be of different types. They alos allow complex data types for their element. So there can be a tuple within a tuple providing a wat to create nested data structure. Capability to create nested data structure is especially useful in iterative and recursive algorithms

In [5]:
bin_colors=('Red','Green','Blue','Yellow')
print(f"The Second element of the tuple is {bin_colors[1]}")

The Second element of the tuple is Green


In [6]:
print(f"the elements after thrid element onwards are {bin_colors[2:]}")

the elements after thrid element onwards are ('Blue', 'Yellow')


Let us define nested tuple data structure

In [7]:
nested_tuple = (1,2,(100,200,300),6)
print(f"The maximum value of the inner tuple {max(nested_tuple[2])}")

The maximum value of the inner tuple 300


## 3. Dictionary

### Dictionary

To create a simple dictionary that assigns colors to varioys variables, the key-values pairs need to be enclosed in{} Fore example, the following code creates a simple dictionary consisting of three key-value pairs

In [8]:
bin_colors= {
    "manual_color" : "Yellow",
    "approved_color" : "Green",
    "refused_color" : "Red"
}

In [9]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [10]:
bin_colors.get('approved_color')

'Green'

In [11]:
bin_colors['approved_color']

'Green'

In [12]:
bin_colors['approved_color']="Purple"

In [13]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


## 4. Sets

### Set

A set is defined as a collection of elements which can be of different types. The elements are enclosed with {}. For example. have a look at the following code block

In [14]:
green = {'grass','leaves'}
print(green)

{'grass', 'leaves'}


In [15]:
yellow = {'dandelions', 'fire hydrant', 'leaves',}
red = {'fire hydrant', 'blood', 'rose', 'leaves'}

In [16]:
print(f"The union of yellow and red sets is {yellow|red}")

The union of yellow and red sets is {'fire hydrant', 'dandelions', 'leaves', 'blood', 'rose'}


In [17]:
print(f"The intersaction of yellow and red is {yellow&red}")

The intersaction of yellow and red is {'fire hydrant', 'leaves'}


## 5. DataFrames

### DataFrame

DataFrame is a data structure used to store tabular data available in Python's pandas package. It is one of the most important data structure for algorithm and is used to process traditional structure data

In [18]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elene', 23, False],
    ['3', 'Setven', 40, True]])
df.columns = ['id', 'name', 'age', 'decision']
print(df)

  id    name  age  decision
0  1   Fares   32      True
1  2   Elene   23     False
2  3  Setven   40      True


### 1.1 Column Selection

The values of name and age columns are

In [19]:
df[['name','age']]

name  age
0   Fares   32
1   Elene   23
2  Setven   40

The positioning of a column is deterministic in a data frame. Fourth column can be retrieved by its position as follows

In [20]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

### 1.2 Row Selection

Each row in DataFrame corresponds to a data-point in our problem space. We need to perform row selection if we want to create a subset of the data elements we have in our 

In [21]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elene   23     False
2  3  Setven   40      True

To create subset by specifying the fiter, we need to use one or more columns to define the selection criterion. For example, a subsete of data elemnts can be selected by this methos as follows

In [22]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Setven   40      True

## 6. Matrix

### Matrix

A matrix is a two-dimensional data structure with a fixed number of columns and rows. Each element of a matrix can be referred to by its column and the row

In [23]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

In [24]:
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [25]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [26]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

# II. Tipe Data Abstrak

## 1. Vector

A vector is a single dimension structure to store data. First, use list. Second, use Array

In [27]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [28]:
print(type(myVector))

<class 'list'>


In [29]:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [30]:
print(type(myVector))

<class 'numpy.ndarray'>


## 2. Stack

### Stack

Stack is a linear data structure to store one dimensional list. It can store items either in Last-in-First-Out (FILO) manner. The defining characteristic of a stack is way elements are added and emoved from it. A new elemnt is added at one end and an element iss removed from that end only

In [31]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.otems[len(self.items)-1]
    def size(self):
        return len(self.items)

To push four elements to the stack following code can be used

# Populate the Stack

In [32]:
stack=Stack()
stack.push('Red')
stack.push('Gree')
stack.push("Blue")
stack.push("Yellow")

### Pop

In [33]:
stack.pop()

'Yellow'

In [34]:
stack.isEmpty()

False

In [35]:
colors = ['Red']

In [36]:
colors.append('Green')
colors.append('Yellow')
colors.append('Blue')

In [37]:
colors

['Red', 'Green', 'Yellow', 'Blue']

## 3. Queue

### Queue

Like stack, queue store n elements in a single-dimensional structure. The elements are added and removed in First-In-First-Out(FIFO) format One end of the queue is called rear and the other one is called the front. The elements are removed from the front. and the operation is called dequeue. The elements are adde at the rear and the operation is acalled enqueue

In [38]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [39]:
queue = Queue()

In [40]:
queue.enqueue("Red")

In [41]:
queue.enqueue('Green')

In [42]:
queue.enqueue('Blue')

In [43]:
queue.enqueue('Yellow')

In [44]:
print(f"Size of queue is {queue.size()}")

Size of queue is 4


In [45]:
print(queue.dequeue())

Red
